export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const REFRESH_BASKET = "REFRESH_BASKET";

export const GET_ALL_ITEMS = "GET_ALL_ITEMS";
export const GET_FIRST_ITEMS = "GET_FIRST_ITEMS";
export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const GET_ALL_MODELS = "GET_ALL_MODELS";
export const GET_ALL_TYPES = "GET_ALL_TYPES";
export const GET_ALL_TASTES = "GET_ALL_TASTES";

export const ADD_FILTER = "ADD_FILTER";
export const DELETE_FILTER = "DELETE_FILTER";
export const RESET_FILTERS = "RESET_FILTERS";

export const UPDATE_COUNT = "UPDATE_COUNT";

export const SET_INDEXES = "SET_INDEXES";

export const SORT_FROM_LOW_PRICE = "SORT_FROM_LOW_PRICE"
export const SORT_FROM_HIGHT_PRICE = "SORT_FROM_HIGHT_PRICE"
export const SORT_NEW_DEVICES = "SORT_NEW_DEVICES"
export const SORT_RATING = "SORT_RATING"